package com.jtrent238.moretrophies.trophyloaders;

import com.jim.obstrophiesaoa.trophy.TrophyAoA;
import com.jim.obstrophiesaoa.trophy.TrophyRegistry;

public class FatherToastSpecialMobs {

	public static void registerTrophies() {


		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "ArmorCreeper")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "BabyCaveSpider")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "BabyGhast")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "BabySpider")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "BlackberrySlime")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "BlindingEnderman")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "BlindingSilverfish")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "BlueberrySlime")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "BrutishPigZombie")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "BrutishSkeleton")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "BrutishZombie")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "CaramelSlime")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "CinderBlaze")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "ConflagrationBlaze")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "CursedEnderman")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "ZombDarkCreeperie")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "DeathCreeper")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "DesertSpider")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "DirtCreeper")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "DominationWitch")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "DoomCreeper")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "DrowningCreeper")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "EmberBlaze")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "EnderCreeper")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "FaintGhast")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "FighterGhast")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "FireCreeper")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "FireSkeleton")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "FireZombie")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "FishingPigZombie")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "FishingSilverfish")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "FishingZombie")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "FlyingCaveSpider")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "FlyingSilverfish")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "FlyingSpider")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "GatlingSkeleton")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "GhostSpider")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "GiantPigZombie")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "GiantSkeleton")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "GiantSpider")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "GiantZombie")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "GrapeSlime")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "GravelCreeper")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "GravityCreeper")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "HellfireBlaze")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "HungryPigZombie")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "HungrySpider")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "HungryZombie")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "IcyEnderman")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "InfernoBlaze")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "JoltBlaze")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "JumpingCreeper")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "KingGhast")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "LemonSlime")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "LightningCreeper")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "LightningEnderman")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "MiniCreeper")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "MiniEnderman")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "MiniGhast")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "MirageEnderman")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "MotherCaveSpider")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "MotherSpider")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "NinjaSkeleton")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "PaleSpider")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "PlaguePigZombie")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "PlagueZombie")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "PoisonSilverfish")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "PoisonSkeleton")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "PoisonSpider")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "QueenGhast")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "RageWitch")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "SMFishHook")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "SMSpitball")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "ShadowsWitch")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "SmallSpider")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "SmolderBlaze")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "SniperSkeleton")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "SpecialBlaze")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "SpecialCaveSpider")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "SpecialCreeper")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "SpecialEnderman")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "SpecialGhast")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "SpecialPigZombie")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "SpecialSilverfish")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "SpecialSkeleton")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "SpecialSlime")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "SpecialSpider")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "SpecialWitch")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "SpecialZombie")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "SpitfireSkeleton")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "SplittingCreeper")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "StrawberrySlime")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "ThiefEnderman")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "ThiefSkeleton")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "ToughCaveSpider")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "ToughSilverfish")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "ToughSpider")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "UndeadWitch")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "UnholyGhast")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "VampirePigZombie")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "WatermelonSlime")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "WebCaveSpider")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "WebSpider")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "WildfireBlaze")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "WildsWitch")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "WindWitch")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "WitchCaveSpider")});
		TrophyRegistry.getInstance().addTrophies(new TrophyAoA[] { new TrophyAoA("SpecialMobs", "WitchSpider")});

	}

}
